title:        电子学基础
description:  xyMeng

theme: null

siteurl: "https://xymeng.xyz/electronics/"

# debug:
#   compress: true
#   dist: false
#   shortcodes: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
