title:        电子学基础
description:  xyMeng

theme: null

url: "https://xym.work"
baseurl: "/electronics"

# debug:
#   compress: true
#   dist: false
#   shortcodes: true

gittalk:
  enable:       true
  clientID:     5c4a4805389461265123
  clientSecret: b13a143f197a4e12a8295c256b366d884ec661d8
  repo:         electronics
  owner:        Meng2025
  admin:        Meng2025
  id:           comments

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
